name: run

on:
  workflow_dispatch:

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: ./run.sh
        run: ./run.sh
  run-macos:
    runs-on: macos-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: brew install podman
        run: brew install podman
      - name: podman machine init
        run: podman machine init
      - name: podman machine start
        run: podman machine start
      - name: ./run.sh
        run: ./run.sh
